accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from django.urls import reverse_lazy
#from django.core.urlresolvers import reverse_lazy

from . import views

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', login, name='login', kwargs={'template_name': 'accounts/login_form.html'}),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^logout/$', logout, name='logout', kwargs={'next_page': reverse_lazy('home')})

]

foodapp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^$', lambda request: redirect('shop:index'), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^category/(?P<pk>\d+)/$', views.category_detail, name='category_detail'),
    url(r'^category/(?P<category_pk>\d+)/shop/(?P<pk>\d+)/$', views.shop_detail, name='shop_detail'),
    url(r'^(?P<pk>\d+)/review/new/$', views.review_new, name='review_new'),

]

accounts/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.core.urlresolvers import reverse
from jsonfield import JSONField

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    icon = models.ImageField(blank=True)
    is_public = models.BooleanField(default=False, db_index=True)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('shop:category_detail', args=[self.pk])


class Shop(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=100, db_index=True)
    desc = models.TextField(blank=True)
    latlng = models.CharField(max_length=100, blank=True)
    photo = models.ImageField(blank=True)
    is_public = models.BooleanField(default=False, db_index=True)
    meta = JSONField()


    def __str__(self):
        return self.name

    @property
    def address(self):
        return self.meta.get('address')

    def get_absolute_url(self):
        return reverse('shop:shop_detail', args=[self.category_id, self.pk])



class Review(models.Model):
    shop = models.ForeignKey(Shop)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    photo = models.ImageField(blank=True)
    rating = models.SmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return self.author


class Item(models.Model):
    shop = models.ForeignKey(Shop) # 특정가게에만 속하도
    name = models.CharField(max_length=100, db_index=True)
    desc = models.TextField(blank=True)
    amount = models.PositiveIntegerField()
    photo = models.ImageField(blank=True)
    is_public = models.BooleanField(default=False, db_index=True)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'message', 'photo']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy


User = get_user_model()



signup = CreateView.as_view(model=User, form_class=UserCreationForm,
                            template_name='accounts/signup_form.html', success_url=reverse_lazy('home'))


@login_required
def profile(request):

    return render(request, 'accounts/profile.html')

def signupnext(request):

    return render(request, 'accounts/signup_next.html')

shop/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import Category, Shop, Review, Item
from .forms import ReviewForm
from django.shortcuts import render, get_object_or_404, redirect
from auth_mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

# Create your views here.
index = ListView.as_view(model=Category)

category_detail = DetailView.as_view(model=Category)

shop_detail = DetailView.as_view(model=Shop)


class ReviewCreateView( LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm

    def form_valid(self, form):
        self.shop = get_object_or_404(Shop, pk=self.kwargs['pk'])
        review = form.save(commit=False)
        review.shop = self.shop
        review.author = self.request.user  # django.contrib.auth.models.AnonymousUser

        return super().form_valid(form)

    def get_success_url(self):
        return self.shop.get_absolute_url()


review_new = ReviewCreateView.as_view( model= Review,form_class=ReviewForm)

accounts/templates/accounts/layout.html
{% extends 'layout.html' %}

accounts/templates/accounts/login_form.html
{% extends 'accounts/layout.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5>로그인 Login</h5>
            <form action="" method="post">
                {% csrf_token %}
                <table class="table table-hover table-bordered">
                    {{form.as_table}}
                </table>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/layout.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>로그아웃 되었습니다.</h3>
            <h4>로그아웃</h4>


        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/layout.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>{{user}}'s Profile'</h3>
            <h4>주문내역</h4>


        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends 'accounts/layout.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5>회원가입 Signup</h5>
            <form action="" method="post">
                {% csrf_token %}
                <table class="table table-hover table-bordered">
                    {{form.as_table}}
                </table>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>

{% endblock %}

foodapp/templates/layout.html
{%  load staticfiles %}
<!doctype html>
<html>
<head>
    <meta charset = "utf-8"/>
    <title> My Food App </title>
    <link rel="stylesheet" href="/static/bootstrap-4.0.0/css/cosmos/bootstrap.min.css"/>


    <script src="{% static 'bootstrap-4.0.0/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

</head>
<body>
    <header class="mb-3">
       <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-2 bg-light border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'shop:index' %}">MY FOOD APP</a></h5>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'accounts:profile' %}">프로필 Profile</a>
            <a class="p-2 text-dark" href="{% url 'accounts:logout' %}">logout</a>


        {% endif %}
      </nav>
      {% if not user.is_authenticated %}
          <a class="btn btn-outline-primary mr-1" href="{% url 'accounts:login' %}">로그인</a>
          <a class="btn btn-outline-primary" href="{% url 'accounts:signup' %}">회원가입</a>
      {% endif %}
    </div>
    </header>

    {% block content %}
    {%  endblock %}

       <hr />
        <div class="container">
            <div class="row">
                <div class="col-sm-12 mb-3">
                    FoodApp
                </div>

            </div>
        </div>
        {% block extra-body %}
        {% endblock %}
    </body>
</html>

shop/templates/shop/category_detail.html
{% extends 'shop/layout.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <h2>{{category.name}}</h2>
        <div class="row">
            {% for shop in category.shop_set.all %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    {% if shop.photo %}
                    <img src="{{shop.photo.url}}" />
                    {# <a href="{{shop.get_absolute_url}}"></a> #}
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">{{shop.name}}</p>
                        <p class="card-text">
                            {{shop.desc}}
                            {{shop.address}}
                            {# {{shop.latlng}} #}
                            {# {{shop.is_public}} #}
                        </p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{shop.get_absolute_url}}" class="btn btn-sm btn-outline-secondary">View</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <hr/>
    <a href="{% url 'shop:index' %}" class='btn btn-primary'>메인화면으로</a>
</div>



{% endblock %}

shop/templates/shop/category_list.html
{% extends 'shop/layout.html' %}
    {% block content %}
<div class="container">
    <div class="row">
        {% for category in category_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                {% if category.icon %}
                    <img class="card-img-top" src="{{category.icon.url}}" />
                {% endif %}
                <div class="card-body">
                    <p class="card-text">{{category.name}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{{category.get_absolute_url}}" class="btn btn-sm btn-outline-secondary">View</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        {% endfor %}
    {% endblock %}
        </div>
    </div>
</div>

shop/templates/shop/layout.html
{% extends 'layout.html' %}

shop/templates/shop/review_form.html
{% extends 'shop/layout.html' %}
{% block content %}



<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5>리뷰를 작성해 주세요!</h5>
            <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
             <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>


{% endblock %}

shop/templates/shop/shop_detail.html
{% extends 'shop/layout.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{shop.name}}</h2>

            <div id="map_view" style="width:500px; height:300px;"></div>
            <img src="https://openapi.naver.com/v1/map/staticmap.bin?clientId={{settings.NAVER_MAP_CLIENT_ID}}&url=http://127.0.0.1:8000&crs=EPSG:4326&center={{shop.meta.lng}},{{shop.meta.lat}}&level=8&w=320&h=320&baselayer=default&markers={{shop.meta.lng}},{{shop.meta.lat}}" alt="">
            <table>

                <tr><th>주소</th><td>{{shop.meta.address}}</td></tr>
                <tr><th>배달비</th><td>{{shop.meta.delivery_fee_explanation}}</td></tr>
                <tr><th>최소주문금액 </th><td>{{shop.meta.min_order_amount}}원</td></tr>
                <tr><th>위도</th><td>{{shop.meta.lat}}</td></tr>
                <tr><th>경도</th><td>{{shop.meta.lng}}</td></tr>
                <tr><th>전화번호</th><td><a href="tel:{{shop.meta.phone}}">{{shop.meta.phone}}</a></td></tr>
            </table>
            <hr>


            <table class="table table-bordered table-hover" id="item-list">
                <tbody>
                    {% for item in shop.item_set.all %}
                    <tr class="item" data-item-id="{{item.id}}">
                        <td>
                            {% if item.photo %}
                            <img src="{{item.photo.url}}" style="width:144px;"/>
                            {% endif %}
                        </td>
                        <td>{{item.name}}</td>
                        <td>{{item.desc}}</td>

                        <td>{{item.amount}}</td>

                        <td>{{item.is_public}}</td>
                        <td>
                            <i class="factor-button fa fa-minus-circle" data-factor="-1"></i>
                            <span class="quantity">0</span>
                            <i class="factor-button fa fa-plus-circle" data-factor="1"></i>
                        </td>


                    </tr>

                    {% endfor %}

                </tbody>
            </table>
            <h5>@ 리뷰 확인하기 Review</h5>
            <a href="{% url "shop:review_new" shop.pk %}" class ="btn btn-primary">리뷰쓰기 Review</a>

            <table>
                <tbody>
                    {% for review in shop.review_set.all  %}
                    <tr>
                        <td>{{ review.author }} : </td>
                        <td>{{ review.message }}</td>


                    </tr>
                    {% endfor %}
                </tbody>
            </table>


        </div>
    </div>
    <hr/>
    <a href="{% url 'shop:index' %}">메인화면으로 </a> |
    <a href="{{shop.category.get_absolute_url}}">{{shop.category.name}} 카테고리로 돌아가기</a>
</div>


{% endblock %}

{% block extra-body %}
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script>
    $(function() {
        $('#item-list .item .factor-button').click(function() {
            var $el = $(this).siblings('.quantity');
            var factor = parseInt($(this).data('factor'));
            var quantity = parseInt($el.html()) + factor;
            if (quantity < 0) quantity = 0;
            $el.html(quantity);
        })
    });

    $('#order-button').click(function() {
        var mapped = _.map($('#item-list .item'), function(item) {
            var item_id = $(item).data('item-id');
            var quantity = $(item).find('.quantity').html();
            return {item_id: item_id, quantity: quantity};
        });

        var filtered = _.filter(mapped, function(item) {
            return item.quantity > 0;
        });

        if (filtered.length >0) {
            var args = $.param(_.object(_.map(filtered, _.values)));
            var url = $(this).attr('href')+'?'+args;
            $(this).attr('href', url);
            return true;
        } else {
            alert('상품 수량을 선택해주세요');
        }
        return false;
    })
    foodmap();
    function foodmap() {


			var lat	= {{shop.meta.lat}}
			var lng	= {{shop.meta.lng}}

			var zoomlv= 16;

			var markerTitle		= "{{shop.name}}";
			var markerMaxWidth	= 300;


			var contentString	= '<div>' +
			'<h5>'+'{{shop.name}}'+'<h5>'+
			'</div>';

			var myLatlng = new google.maps.LatLng(lat, lng);
			var mapOptions = {
								zoom: zoomlv,
								center: myLatlng,
								mapTypeId: google.maps.MapTypeId.ROADMAP
			}
			var map = new google.maps.Map(document.getElementById('map_view'), mapOptions);

			var marker = new google.maps.Marker({
													position: myLatlng,
													map: map,
													title: markerTitle
			});

			var infowindow = new google.maps.InfoWindow(
														{
															content: contentString,
															maxWidth: markerMaxWidth
														}
			);

			google.maps.event.addListener(marker, 'click', function() {
				infowindow.open(map, marker);
			});
		}
</script>
{% endblock %}